<?php

defined('BOOTSTRAP') or die('Access denied');

const BEST2PAY_PROCESSOR = 'best2pay.php';
const BEST2PAY_OPERATION_APPROVED = 'APPROVED';
const BEST2PAY_SUPPORTED_TYPES = [
	'PURCHASE',
	'PURCHASE_BY_QR',
	'AUTHORIZE',
	'REVERSE',
	'COMPLETE'
];
const BEST2PAY_PAYMENT_TYPES = [
	'PURCHASE',
	'PURCHASE_BY_QR',
	'AUTHORIZE'
];